[package]
name = "final_lab"
version = "0.1.0"
edition = "2024"

[dependencies]
pest = "2.8" 
pest_derive = "2.8"
graphlib = "0.6.3"

[[bin]]
name = "ssmv"
path = "src/main.rs"

[[bin]]
name = "deadlock"
path = "src/deadlock/main.rs"
